- name: passing variables
  hosts: localhost
  vars:
    course: "DevOps"
    trainer: "SivaKumar"
    duration: "120hrs"
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: Hi, this is {{course}}, trainer is {{trainer}} and course duration is {{duration}}