- name: passing variables
  hosts: localhost
  vars:  # variable deeclaration
    course: "DevOps"
    trainer: "SivaKumar"
    duration: "120hrs"
  tasks:
  - name: # print information
    ansible.builtin.debug:
      msg: Hi, this is {{course}}, trainer is {{trainer}} and course duration is {{duration}}