- name: 
  hosts: localhost
  vars:
    course: devops
    trainer: sivakumar
    duration: 120hrs
  tasks:
  - name:
    vars:
      trainer: raghu
    ansible.builtin.debug:
     msg: hi, this is {{course}}, trainer is {{trainer}} and duration is {{duration}}

- name:
  tasks:
  ansible.builtin.debug:
    msg: hi, this is trainer {{trainer}}