- name: 
  hosts: localhost
  vars:
    course: devops
    trainer: sivakumar
    duration: 120hrs
  tasks:
  - name: printing override information
    vars: #task level variables
      trainer: raghu
    ansible.builtin.debug:
     msg: hi, this is {{course}}, trainer is {{trainer}} and duration is {{duration}}

  - name:
    ansible.builtin.debug:
      msg: hi, this is {{trainer}} # prints sivakumar as trainer