- name: variables from file
  hosts: localhost
  vars_files:  #calling variables from file
  - vars.yaml
  tasks:
  - name:
    ansible.builtin.debug:
      msg: hi, this is {{course}}, trainer is {{trainer}} and duration is {{duration}}