- name:
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: please enter username
      private: false
    - name: PASSWORD
      prompt: please enter password
      private: true
  tasks:
  - name:
    ansible.builtin.debug:
      msg: hi, this is {{USERNAME}} and password is {{PASSWORD}}