- name: taking variables from inventory
  hosts: localhost
  tasks:
  - name: printing variables
    ansible.builtin.debug:
     msg: hi, this is {{course}}, trainer is {{trainer}} and duration is {{duration}} 