- name: using conditions
  hosts: localhost
  become: yes
  tasks:
    - name: check user
      ansible.builtin.command: id expense
      register: USER #saving success or failure output of above command in USER
      ignore_errors: true

    - name: print user
      ansible.builtin.debug:
        msg: "{{USER}}""
        
    - name: create user
      ansible.builtin.command: useradd expense
      when: USER.rc != 0 #condition

