- name: default value
  hosts: localhost
  tasks:
  - name: print deefault value
    ansible.builtin.debug:
      msg: "this course is {{ course | default('ansible') }}"

  tasks:
  - name: upper case
    vars:
      greeting: Hello, Good Morning
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"