- name: default value
  hosts: localhost
  tasks:
  - name: print deefault value
    ansible.builtin.debug:
      msg: "this course is {{ course | default('ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: Hello, Good Morning
  tasks:
  - name: print upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: Hello, Good Morning
  tasks:
  - name: print lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 5, 6, 6, 10]
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max ages in list
  hosts: localhost
  vars:
    ages: [23, 25, 33, 45, 50]
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "min age is {{ ages | min }}, max age is {{ ages | max }}"