- name: basic loop 
  hosts: localhost
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "{{item}}" # item is a reserved keyword in ansible
    loop: # item check the loop to go over individually
    - ansible
    - nginx
    - mysql

